(* Generated by           *
 *             CamlTrax   *
 *                     NG *
 *                        *
 * Copyright 2007-2023    *
 *             K.D.P.Ross *)


let error = ( print_endline )


let warn = ( print_endline )


let warnClosure  k = ( warn ( k () ) )

