(* Generated by           *
 *             CamlTrax   *
 *                     NG *
 *                        *
 * Copyright 2007-2023    *
 *             K.D.P.Ross *)


type topLevelExp = TLBind of ( string * SurfaceSyntax.typ * SurfaceSyntax.exp )
                 | TLExp of SurfaceSyntax.exp

